/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eriksandsten_chromedtp_utils_WHelper */

#ifndef _Included_com_eriksandsten_chromedtp_utils_WHelper
#define _Included_com_eriksandsten_chromedtp_utils_WHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eriksandsten_chromedtp_utils_WHelper
 * Method:    setActiveWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_eriksandsten_chromedtp_utils_WHelper_setActiveWindow__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_eriksandsten_chromedtp_utils_WHelper
 * Method:    setActiveWindow
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eriksandsten_chromedtp_utils_WHelper_setActiveWindow__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eriksandsten_chromedtp_utils_WHelper
 * Method:    getWindowHandlesByWindowClassName
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_eriksandsten_chromedtp_utils_WHelper_getWindowHandlesByWindowClassName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
